### ISSUE TITLE
underlined() does not work if srt != 0

### ISSUE THREAD

**Issue by chrisdane** [ellisztamas/arghqtl#1]
Hi 

Thanks for the great `underlined()` function. Unfortunately, it does not work if the `text()` arg `srt` is not equal 0, i.e. the text is not horizontal (default) but rotated by angle `srt`.

Best,
Chris

**Comment by ellisztamas** [comment]
Thanks for spotting this and the other issue about log scales at https://github.com/ellisztamas/arghqtl/issues/2#issue-585471239.

It probably isn't worth creating a really robust version of this function when you can also use `bquote` (for example: https://stackoverflow.com/questions/23988052/underline-text-in-a-barplot-in-r). I've updated the man files to make clear the limitation of the function.
