### ISSUE TITLE
underlined() does not work on logarithmic y-axis

### ISSUE THREAD

**Issue by chrisdane** [ellisztamas/arghqtl#2]
Hi

If a plot was opened with, e.g. `plot(x, y, log="y")`, the `underlined()` function does not work.

Best,
Chris

**Comment by ellisztamas** [comment]
Thanks for spotting this and the other issue about text at an angle at https://github.com/ellisztamas/arghqtl/issues/1#issue-585470539.

As for the other issue It probably isn't worth creating a really robust version of this function when you can also use `bquote` (for example: https://stackoverflow.com/questions/23988052/underline-text-in-a-barplot-in-r). I've updated the man files to make clear the limitation of the function.
